jannikbecker/leibit

- Leibit.Client.WPF/Windows/SystemState/Views/SystemStateView.xaml
- Leibit.Client.WPF/Windows/TimeTable/Views/TimeTableView.xaml
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGrid.xaml.cs
- Leibit.Core.Client.WPF/Common/DataGridUtils.cs
Added possibility to add default layouts to datagrids. Implemented default layouts for all available data grids.
Resolves #1
> Datagrid default layout

- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableItemViewModel.cs
- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableViewModel.cs
- Leibit.Client.WPF/Windows/TimeTable/Views/TimeTableView.xaml
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainStationViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGrid.xaml.cs
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGridColumn.cs
> Sortierung ZFI/BFO

- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayInfoViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayJustificationViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayReason.cs
- Leibit.Client.WPF/Windows/DelayJustification/Views/DelayJustificationView.xaml
- Leibit.Core.Client.WPF/Common/ComboBoxTemplateSelector.cs
Codierung der Verspätungsbegründungen ergänzt
> Added delay justification codes

- Leibit.Tests/Utils/ESTWOnlineScope.cs
- Leibit.Tests/Utils/ESTWTestDataScope.cs
> Test commit

- Leibit.Client.WPF/Windows/TimeTable/Views/TimeTableView.xaml
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
> Scrollverhalten in ZFI und BFO

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/RSI.xml
- Leibit.Core/Leibit.Core.csproj
> Singen hinzugefügt. #32

- Leibit.BLL/CalculationBLL.cs
- Leibit.Entities/LiveData/LiveSchedule.cs
- Leibit.Entities/LiveData/TrainInformation.cs
- Leibit.Tests/CalculationBLLTest.cs
> Berechnung der erwarteten Zeiten

- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayReason.cs
Reason 41 was missing, which should be available, e.g. for ESTW Singen.
> Add missing Delay Reason

- Leibit.BLL/Constants.cs
- Leibit.BLL/InitializationBLL.cs
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
- Leibit.Client.WPF/Windows/TrainComposition/ViewModels/TrainCompositionViewModel.cs
- Leibit.Client.WPF/Windows/TrainComposition/Views/TrainCompositionView.xaml
- Leibit.Client.WPF/Windows/TrainComposition/Views/TrainCompositionView.xaml.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Entities/Enums.cs
- Leibit.Entities/Scheduling/Train.cs
- Leibit.Tests/Comparer/TrainComparer.cs
- Leibit.Tests/ExpectedData/ExpectedValuesOfInitializationBLLTest.cs
- Leibit.Tests/Leibit.Tests.csproj
- Leibit.Tests/TestData/ESTWRoots/Testdorf/Zugbildung/02007___.zug
> Zugbildung

- Leibit.Client.WPF/Views/MainView.xaml
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayInfoViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayJustificationViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/Views/DelayJustificationView.xaml
- Leibit.Core.Client.WPF/Common/FocusManager.cs
Focus behaviour in the delay justification window and the train schedule drop-down has been improved.
> Improve focus behaviour

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MWH.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MWH

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MWKR.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MWKR

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MGE.xml
- Leibit.Core/Data/sued/MWH.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MGE

- Leibit.Client.WPF/Dialogs/Error/ErrorDialog.cs
- Leibit.Client.WPF/Dialogs/Error/ErrorDialogView.xaml
- Leibit.Client.WPF/Dialogs/Error/ErrorDialogView.xaml.cs
- Leibit.Client.WPF/Dialogs/Error/ErrorDialogViewModel.cs
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
> Improve error handling

- Leibit.BLL/CalculationBLL.cs
- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableViewModel.cs
- Leibit.Entities/Common/Station.cs
- Leibit.Entities/Scheduling/Schedule.cs
> Fix unscheduled trains in ZFI

- Leibit.BLL/LiveDataBLL.cs
- Leibit.Client.WPF/Interfaces/IRefreshable.cs
- Leibit.Client.WPF/ViewModels/ChildWindowViewModelBase.cs
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayJustificationViewModel.cs
- Leibit.Client.WPF/Windows/ESTWSelection/ViewModels/ESTWSelectionESTWViewModel.cs
- Leibit.Client.WPF/Windows/ESTWSelection/ViewModels/ESTWSelectionViewModel.cs
- Leibit.Client.WPF/Windows/ExpectedDelay/ViewModels/ExpectedDelayViewModel.cs
- Leibit.Client.WPF/Windows/SystemState/ViewModels/LiveTrainViewModel.cs
- Leibit.Client.WPF/Windows/SystemState/ViewModels/SystemStateViewModel.cs
- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableViewModel.cs
- Leibit.Client.WPF/Windows/TrackChange/ViewModels/TrackChangeViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Client.WPF/Windows/TrainSchedule/ViewModels/TrainScheduleViewModel.cs
- Leibit.Client.WPF/Windows/TrainState/ViewModels/TrainStateViewModel.cs
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGrid.xaml.cs
- Leibit.Entities/LiveData/RefreshLiveDataResult.cs
> Fix refresh and grid sorting

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MAHZ.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MAHZ

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MOL.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MOL

- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGrid.xaml.cs
> Fix grid sorting issue

- Leibit.Client.WPF/Windows/TimeTable/Views/TimeTableView.xaml
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Controls.WPF/LeibitDataGrid/ColumnBackgroundCondition.cs
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGrid.xaml.cs
- Leibit.Controls.WPF/LeibitDataGrid/LeibitDataGridColumn.cs
- Leibit.Core.Client.WPF/Common/BindingExtensions.cs
A possibility to print the content of LeibitDataGrid has been added. This resolves #9 .
> Print DataGrids

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/sued/MIMS.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented MIMS

- Leibit.BLL/InitializationBLL.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayInfoViewModel.cs
- Leibit.Client.WPF/Windows/DelayJustification/ViewModels/DelayReason.cs
- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/Areas.xsd
- Leibit.Entities/Common/ESTW.cs
- Leibit.Entities/Enums.cs
- Leibit.Tests/TestData/Areas.xml
> Delay reasons for ÖBB

- Leibit.BLL/InitializationBLL.cs
- Leibit.BLL/LiveDataBLL.cs
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
- Leibit.Client.WPF/Windows/ESTWSelection/ViewModels/ESTWSelectionESTWViewModel.cs
- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/ESTW.xsd
- Leibit.Core/Data/nord/HBSB.xml
- Leibit.Core/Leibit.Core.csproj
- Leibit.Entities/Common/ScheduleFile.cs
- Leibit.Entities/Common/Station.cs
- Leibit.Tests/ExpectedData/ExpectedValuesOfInitializationBLLTest.cs
- Leibit.Tests/InitializationBLLTest.cs
- Leibit.Tests/Leibit.Tests.csproj
- Leibit.Tests/Properties/Resources.Designer.cs
- Leibit.Tests/Properties/Resources.resx
- Leibit.Tests/TestData/Areas.xml
- Leibit.Tests/TestData/ESTWRoots/ScheduleTest/Bahnhof Fahrplan/G1______.dat
- Leibit.Tests/TestData/ESTWRoots/ScheduleTest/Bahnhof Fahrplan/G2______.dat
- Leibit.Tests/TestData/ST.xml
Resolves #18 
Additional logic needed to be implemented due to multiple and partially overlapping schedule files in HBSB, HBAW and HAW.
> Implemented HBSB

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nord/ABLZ.xml
- Leibit.Core/Data/nord/HSO.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented HSO

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nord/HV.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented HV

- Leibit.BLL/InitializationBLL.cs
- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nord/HNBG.xml
- Leibit.Core/Leibit.Core.csproj
- Leibit.Tests/ExpectedData/ExpectedValuesOfInitializationBLLTest.cs
- Leibit.Tests/TestData/ESTWRoots/ScheduleTest/Bahnhof Anweisungen/bf1_____.abf
Resolves #20 
A fix was needed for reading local orders as the local orders files may contain tabular characters (\t).
> Implemented HNBG

- Leibit.BLL/InitializationBLL.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PlatformDisplayViewModel.cs
- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/ESTW.xsd
- Leibit.Core/Data/nrw/KKM.xml
- Leibit.Core/Leibit.Core.csproj
- Leibit.Entities/Common/Station.cs
> Implemented KKM

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nrw/KSO.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented KSO

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nrw/KW.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented KW

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nrw/KWO.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented KWO

- Leibit.BLL/InitializationBLL.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DepartureBoardViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PassengerInformationViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PlatformDisplayViewModel.cs
- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableItemViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/Views/TrainProgressInformationView.xaml
- Leibit.Core/Common/Extender.cs
- Leibit.Core/Data/passenger_trains.json
- Leibit.Core/Leibit.Core.csproj
- Leibit.Entities/Scheduling/Schedule.cs
> Train types

- Leibit.BLL/LiveDataBLL.cs
- Leibit.BLL/SerializationBLL.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Entities/LiveData/LiveSchedule.cs
- Leibit.Entities/Serialization/SerializedSchedule.cs
> Fix disappearing trains

- Leibit.BLL/SettingsBLL.cs
- Leibit.Client.WPF/Windows/Settings/ViewModels/SettingsViewModel.cs
- Leibit.Client.WPF/Windows/Settings/Views/SettingsView.xaml
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Entities/Enums.cs
- Leibit.Entities/LiveData/LiveSchedule.cs
- Leibit.Entities/Settings/Settings.cs
> Random ready message

- Leibit.BLL/InitializationBLL.cs
- Leibit.BLL/LiveDataBLL.cs
- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/fehmarn/APU.xml
- Leibit.Core/Data/fehmarn/Fehmarn.xml
- Leibit.Core/Leibit.Core.csproj
- Implemented ESTW Fehmarn & Puttgarden
- Fix schedule handling for the case that a train passes a station more than one time (like in ANN).
- Fix parsing of local orders files. Local orders in APU have a slightly different format and were not parsed correctly.
Resolves #55 and #56
> Implemented Fehmarn

- Leibit.Client.WPF/Leibit.Client.WPF.csproj
- Leibit.Controls.WPF/Leibit.Controls.WPF.csproj
- Leibit.Core.Client.WPF/Leibit.Core.Client.WPF.csproj
- Leibit.Tests/Leibit.Tests.csproj
> Convert projects to .NET 6

- Leibit.BLL/SettingsBLL.cs
> Move settings file to new location

- Leibit.BLL/SoftwareInfoBLL.cs
- Leibit.Client.WPF/Windows/Settings/Views/SettingsView.xaml
> Path optimization

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/tauern/Ma.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented Ma

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/tauern/Bag.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented Bag

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/tauern/Swa.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented Swa

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/tauern/Bo.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented Bo

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/tauern/Hl.xml
- Leibit.Core/Leibit.Core.csproj
> Implemented Hl

- Leibit.Core/Data/passenger_trains.json
> #212 Add car shuttle trains to list of passenger train types

- Leibit.Client.WPF/Windows/Display/ViewModels/CountdownDisplayViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DepartureBoardViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PassengerInformationViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PlatformDisplayViewModel.cs
> #214 Fix exceptions in displays for cancelled trains at start station

- Leibit.BLL/LiveDataBLL.cs
- Leibit.BLL/SerializationBLL.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/ExpectedDelay/ViewModels/ExpectedDelayViewModel.cs
- Leibit.Client.WPF/Windows/SystemState/ViewModels/LiveTrainViewModel.cs
- Leibit.Client.WPF/Windows/SystemState/Views/SystemStateView.xaml
- Leibit.Client.WPF/Windows/TimeTable/ViewModels/TimeTableViewModel.cs
- Leibit.Client.WPF/Windows/TrackChange/ViewModels/TrackChangeViewModel.cs
- Leibit.Client.WPF/Windows/TrainProgressInformation/ViewModels/TrainProgressInformationViewModel.cs
- Leibit.Client.WPF/Windows/TrainSchedule/ViewModels/TrainScheduleViewModel.cs
- Leibit.Entities/LiveData/TrainInformation.cs
- Leibit.Entities/Serialization/SerializedTrain.cs
> Last train modification

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nord/HNBG.xml
- Leibit.Core/Data/nord/HWUN.xml
- Leibit.Core/Data/nord/TrainNumbers.xml
- Leibit.Core/Leibit.Core.csproj
> #215 Integrated ESTW Wunstorf

- Leibit.Core/Data/Areas.xml
- Leibit.Core/Data/nord/HM.xml
- Leibit.Core/Data/nord/HNBG.xml
- Leibit.Core/Leibit.Core.csproj
> #216 Implemented ESTW Minden

- Leibit.BLL/Leibit.BLL.csproj
- Leibit.BLL/SerializationBLL.cs
- Leibit.BLL/SoftwareInfoBLL.cs
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
- Leibit.Client.WPF/Views/MainView.xaml
- Leibit.Client.WPF/Windows/FileConversion/ViewModels/FileConversionViewModel.cs
- Leibit.Client.WPF/Windows/FileConversion/ViewModels/FileViewModel.cs
- Leibit.Client.WPF/Windows/FileConversion/Views/FileConversionView.xaml
- Leibit.Client.WPF/Windows/FileConversion/Views/FileConversionView.xaml.cs
- Leibit.Core/Leibit.Core.csproj
- Leibit.Core/Scheduling/LeibitTime.cs
- Leibit.Core/Serialization/UntypedPropertyJsonConverter.cs
- Leibit.Entities/Enums.cs
- Leibit.Entities/Leibit.Entities.csproj
- Leibit.Entities/Serialization/SerializationContainer.cs
- Leibit.Entities/Serialization/SerializedWindowInformation.cs
- Change target framework for all projects to .NET 6
- Replace binary serialization by Json
- Add conversion tool
> Update target framework to .NET 6

- Leibit.BLL/Leibit.BLL.csproj
- Leibit.BLL/SerializationBLL.cs
- Leibit.BLL/SoftwareInfoBLL.cs
- Leibit.Client.WPF/Leibit.Client.WPF.csproj
- Leibit.Client.WPF/ViewModels/MainViewModel.cs
- Leibit.Client.WPF/Views/MainView.xaml
- Leibit.Client.WPF/Windows/FileConversion/ViewModels/FileConversionViewModel.cs
- Leibit.Client.WPF/Windows/FileConversion/ViewModels/FileViewModel.cs
- Leibit.Client.WPF/Windows/FileConversion/Views/FileConversionView.xaml
- Leibit.Client.WPF/Windows/FileConversion/Views/FileConversionView.xaml.cs
- Leibit.Core/Leibit.Core.csproj
- Leibit.Core/Scheduling/LeibitTime.cs
- Leibit.Core/Serialization/UntypedPropertyJsonConverter.cs
- Leibit.Entities/Enums.cs
- Leibit.Entities/Leibit.Entities.csproj
- Leibit.Entities/Serialization/SerializationContainer.cs
- Leibit.Entities/Serialization/SerializedWindowInformation.cs
- assets/release_notes.md
- Redesign of status bar
- Change binary serialization to Json incl. conversion tool
> Version 1.1.1

- Leibit.BLL/InitializationBLL.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/ArrivalBoardViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/CountdownDisplayViewModel.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/DisplayViewModelBase.cs
- Leibit.Client.WPF/Windows/Display/ViewModels/PlatformDisplayViewModel.cs
- Set train lines correctly
- Don't display follow-up services when they depart from a different track
> Display fixes
